# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).


In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape (7, 7).

In [1]:
# Import torch
import torch

# Create random tensor
torch.rand(7,7)

tensor([[0.0416, 0.2432, 0.4920, 0.3199, 0.0592, 0.0659, 0.1383],
        [0.4136, 0.6571, 0.8839, 0.8738, 0.2669, 0.3505, 0.9486],
        [0.5983, 0.4291, 0.8683, 0.6311, 0.8153, 0.3301, 0.6763],
        [0.8702, 0.6907, 0.5066, 0.7432, 0.0061, 0.5795, 0.3222],
        [0.0985, 0.9307, 0.2538, 0.9695, 0.0831, 0.2705, 0.0517],
        [0.6777, 0.7649, 0.9396, 0.5099, 0.6459, 0.3689, 0.9958],
        [0.5018, 0.6674, 0.9456, 0.4723, 0.0132, 0.7839, 0.8841]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [11]:
tensor_1 = torch.rand(7, 7)
tensor_2 = torch.rand(1, 7)

tensor_1.matmul(tensor_2.T) # transpose를 사용하여 행렬 곱셈 수행

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [18]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_1 = torch.rand(7, 7)
random_tensor_2 = torch.rand(7, 1)

# random_tensor_1, random_tensor_1.shape, random_tensor_2, random_tensor_2.shape

# Matrix multiply tensors
matmul_result = random_tensor_1.matmul(random_tensor_2)
matmul_result, matmul_result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
torch.mps.manual_seed(1234)
mps_tensor = torch.rand(7,1)
mps_tensor

tensor([[0.8163],
        [0.4423],
        [0.2768],
        [0.8998],
        [0.0960],
        [0.5537],
        [0.3953]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:

# Set random seed
torch.mps.manual_seed(1234)

# Check for access to MPS
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on mps
tensor_1 = torch.rand(2, 3).to(device)
tensor_2 = torch.rand(2, 3).to(device)

tensor_1, tensor_2

Device: mps


(tensor([[0.3603, 0.6477, 0.9110],
         [0.6359, 0.2634, 0.2650]], device='mps:0'),
 tensor([[0.0273, 0.6080, 0.2194],
         [0.0542, 0.9384, 0.1753]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [33]:
# Perform matmul on tensor_A and tensor_B
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(2, 3)

maxmul_tensors = tensor_A.matmul(tensor_B.T)
result = maxmul_tensors.to(device)
result, result.shape

(tensor([[0.2946, 0.3957],
         [0.4857, 0.8738]], device='mps:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [35]:
result.max(), result.min()

(tensor(0.8738, device='mps:0'), tensor(0.2946, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [36]:
result.argmax(), result.argmin()

(tensor(3, device='mps:0'), tensor(0, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [65]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
x = torch.rand(1, 1, 1, 10)

# Remove single dimensions
x_squeezed = x.squeeze()


# Print out tensors and their shapes
print(x, x.shape)
print(x_squeezed, x_squeezed.shape)

tensor([[[[0.4986, 0.2578, 0.9991, 0.9883, 0.1229, 0.0947, 0.1210, 0.4976,
           0.3725, 0.1727]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4986, 0.2578, 0.9991, 0.9883, 0.1229, 0.0947, 0.1210, 0.4976, 0.3725,
        0.1727]) torch.Size([10])


In [66]:
x_unsqeezed = x.unsqueeze(dim=0)

x_reshaped = x.reshape(1,1,1,1,1,1,10)

print(x_unsqeezed, x_unsqeezed.shape)
print(x_reshaped, x_reshaped.shape)

tensor([[[[[0.4986, 0.2578, 0.9991, 0.9883, 0.1229, 0.0947, 0.1210, 0.4976,
            0.3725, 0.1727]]]]]) torch.Size([1, 1, 1, 1, 10])
tensor([[[[[[[0.4986, 0.2578, 0.9991, 0.9883, 0.1229, 0.0947, 0.1210, 0.4976,
              0.3725, 0.1727]]]]]]]) torch.Size([1, 1, 1, 1, 1, 1, 10])


In [64]:
x_stacked = torch.stack([x_squeezed, x_squeezed], dim=0)
print(x_stacked, x_stacked.shape)


tensor([[0.7898, 0.4503, 0.6522, 0.3794, 0.6752, 0.1378, 0.2060, 0.2462, 0.9595,
         0.3655],
        [0.7898, 0.4503, 0.6522, 0.3794, 0.6752, 0.1378, 0.2060, 0.2462, 0.9595,
         0.3655]]) torch.Size([2, 10])
