In [2]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

# Check PyTorch access (should print out a tensor)
# print(torch.randn(3, 3))

# Check for GPU (should return True)
# print(torch.cuda.is_available())

print(torch.__version__)
print(f"MPS 장치를 지원하도록 build가 되었는가? {torch.backends.mps.is_built()}")
print(f"MPS 장치가 사용 가능한가? {torch.backends.mps.is_available()}") 

# 디바이스 설정
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(f"사용 디바이스: {device}")


e = torch.rand(5, 3)
print(e)

2.4.0
MPS 장치를 지원하도록 build가 되었는가? True
MPS 장치가 사용 가능한가? True
사용 디바이스: mps
tensor([[0.6418, 0.9082, 0.3853],
        [0.1920, 0.6369, 0.7768],
        [0.3782, 0.3077, 0.8622],
        [0.3065, 0.7926, 0.2575],
        [0.8374, 0.7644, 0.8989]])


## Introduction to Tensors

### 1. Creating Tensors
Pytorch tensors are created using`torch.tensor() = https://pytorch.org/docs/stable/tensors.html`

In [3]:

# scalar
print("\n\n########## SCALAR")
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim) # scalar의 차원

# Get tensor back as Python int
print(scalar.item()) # scalar의 값



########## SCALAR
tensor(7)
0
7


In [4]:

# Vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim) # vector의 차원
print(vector.shape) # vector의 크기



########## VECTOR
tensor([7, 7])
1
torch.Size([2])


In [5]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(MATRIX)
print(MATRIX.ndim) # matrix의 차원
print(MATRIX[1])
print(MATRIX.shape) # matrix의 크기

tensor([[ 7,  8],
        [ 9, 10]])
2
tensor([ 9, 10])
torch.Size([2, 2])


In [7]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3,],
                        [3,6,9,],
                        [3,5,4]]])
print(TENSOR)
print(TENSOR.ndim) # tensor의 차원
print(TENSOR.shape) # tensor의 크기
print(TENSOR[0][0]) # 0번째 텐서의 0번째 요소

tensor([[[1, 2, 3],
         [3, 6, 9],
         [3, 5, 4]]])
3
torch.Size([1, 3, 3])
tensor([1, 2, 3])


### Random tensors

#### Why Random Tensors?
- Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

- 데이터 분석 및 모델 테스트를 위해 무작위 데이터를 생성하는 것이 중요.
- 무작위 데이터를 생성하면 모델이 데이터를 학습하고 예측하는 능력을 평가할 수 있음.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `


In [8]:
print("\n\n########## RANDOM TENSORS")

#Create random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)
print(random_tensor)
print(random_tensor.ndim)# 텐서의 차원
print(random_tensor.shape)# 텐서의 크기



########## RANDOM TENSORS
tensor([[[0.1384, 0.2180, 0.6383, 0.4042],
         [0.1864, 0.4526, 0.3141, 0.4745],
         [0.5441, 0.7380, 0.3949, 0.8289]]])
3
torch.Size([1, 3, 4])


In [9]:
# Create random tensor with similar shape to an image
random_image_size_tensor = torch.rand(224, 224, 3) # 높이, 너비, 색상 채널
print(random_image_size_tensor.shape, random_image_size_tensor.ndim)

torch.Size([224, 224, 3]) 3


### Zerps and ones

In [10]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
# Create a tensor of all ones 
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
ones.dtype

torch.float32

In [14]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.range() and get deprecated message, use torch.arange() instead
one_to_ten = torch.arange(start=1, end=1000, step=77) # 1부터 1000까지 77씩 증가하는 텐서
one_to_ten = torch.arange(start=1, end=11, step=1) # 1부터 10까지 1씩 증가하는 텐서
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
torch.__version__

'2.4.0'

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data types

**Note** : Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning.

1. Tensors not data types
2. Tensors not device
3. Tensors not shape


Precision in computing = 데이터의 정밀도
https://en.wikipedia.org/wiki/Precision_(computer_science)

> 데이터 타입, 장치, 형태를 관리하는 것은 PyTorch에서 딥 러닝 모델 작성 시 필수적인 작업입니다.

#### 데이터 타입의 종류
- PyTorch에서 지원하는 주요 데이터 타입:
	- float16, float32, float64: 부동 소수점 숫자.
	- int8, int16, int32, int64: 정수.
	- bool: 논리값.
	- complex32, complex64: 복소수.
- 데이터 타입은 정밀도와 메모리 사용량에 영향을 미칩니다.
	- float16: 더 적은 메모리를 사용하며 연산 속도가 빠르지만, 정밀도가 낮습니다.
	- float32: 기본 데이터 타입으로, 적당한 정밀도와 메모리 사용량을 가집니다.
	- float64: 높은 정밀도와 더 많은 메모리 사용량.

#### 데이터 타입 선택의 중요성
- 정밀도:
	- float16: 메모리 절약 및 빠른 계산이 필요한 경우.
	- float32: 일반적인 상황에서 사용.
	- float64: 높은 정밀도가 필요한 경우.
- 메모리 및 성능:
	- 더 낮은 비트 수의 데이터 타입(float16)은 더 적은 메모리를 사용하고 계산 속도가 빠름.

#### 실수할 수 있는 주요 문제
1.	데이터 타입 불일치:
	- 서로 다른 데이터 타입의 텐서로 연산을 시도할 경우 오류 발생.
2.	장치 불일치:
	- 텐서가 CPU와 GPU에 각각 위치할 경우 연산 불가능.
	- 동일한 장치로 이동 필요:
3.	형태 불일치:
	- 텐서의 차원이나 크기가 다르면 연산 불가능.

In [54]:
# Float 32 tensor 
# 단일 정밀도
# 대부분의 경우 32비트 정밀도를 사용하는 것이 좋음.
# 메모리를 많이 사용하지만 정밀도가 높음.(더 정밀한 작업이 필요한 경우 64비트 정밀도를 사용)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=torch.float32, # 데이터 타입을 지정하고 싶다면 dtype 매개변수를 사용 | What datatype is the tensor(e.g. float32 or float16) - 부동 소수점, 정수, 복소수 등 선택 가능.
                               device="mps", # 텐서가 위치할 장치('cuda(gpu)', 'mps', 'cpu') | What device is your tensor on?
                               requires_grad=False # 텐서의 그래디언트를 추적할지 여부. | 기본값은 False, 역전파 계산에 필요할 경우 True로 설정.
                               )

float_32_tensor

tensor([True, True, True], device='mps:0')

In [46]:
float_32_tensor.dtype

torch.float32

In [53]:
# Float 16 tensor
# 하프 플로트 타입은 메모리를 절반으로 줄이고 속도를 높일 수 있음.
# 정밀도가 낮음.
# float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
# float_16_tensor

float_16_tensor = float_32_tensor.to(torch.half)
float_16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [49]:
float_16_tensor.dtype


torch.float16

In [52]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], device='mps:0')